const bondDatasMock = [
  {
    key: '1',
    name: 'CHM-DALP',
    status: 'opened',
    from: '/images/bond/dfsIcon.png',
    to: '/images/bond/usdtIcon.png',
    price: 1.34,
    discount: 3.23,
    duration: 1,
    balance: 0,
    maxFee: '32415OHM',
    getFee: '0Dao',
  },
  {
    key: '2',
    name: 'CHM-DALP',
    status: 'closed',
    from: '/images/bond/dfsIcon.png',
    to: '/images/bond/bnbIcon.png',
    price: 1.34,
    discount: -3.23,
    duration: 1,
    balance: 0,
    maxFee: '32415OHM',
    getFee: '0Dao',
  },
  {
    key: '3',
    name: 'CHM-DALP',
    status: 'closed',
    from: '/images/bond/dfsIcon.png',
    to: '/images/bond/ethIcon.png',
    price: 1.34,
    discount: -3.23,
    duration: 1,
    balance: 0,
    maxFee: '32415OHM',
    getFee: '0Dao',
  },
]

export default bondDatasMock;